# Generated by Django 4.2.5 on 2023-09-08 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0003_person_myperson'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myperson',
            options={},
        ),
    ]
